ifndef QCONFIG
QCONFIG=qconfig.mk
endif
include $(QCONFIG)

ALL_DEPENDENCIES=$(PROJECT_ROOT)/Makefile
INSTALLDIR=/dev/null
PUBLIC_INCVPATH=$(PROJECT_ROOT)/public

include $(MKFILES_ROOT)/qmacros.mk

#####AUTO-GENERATED by packaging script... do not checkin#####
   INSTALL_ROOT_nto = $(PROJECT_ROOT)/../../../../../install
   USE_INSTALL_ROOT=1
##############################################################

include $(MKFILES_ROOT)/qtargets.mk

